# fly.toml app configuration file generated for memberops-api on 2026-01-20T15:24:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memberops-api'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_URLS = 'http://+:8080'
  Jwt__Audience = 'MemberOpsClient'
  Jwt__ExpiresInMinutes = '60'
  Jwt__Issuer = 'MemberOpsAPI'
  Cors__AllowedOrigins__0 = 'https://memberops-frontend.fly.dev'
  Cors__AllowedOrigins__1 = 'http://localhost:4200'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
